[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cochain"
version = "0.1.0"
description = "Differentiable Simplicial Computation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jaxtyping>=0.3.3",
    "numpy>=2.3.4",
    "pytetwild>=0.1.1",
    "pyvista[jupyter]>=0.46.4",
    "scipy>=1.16.3",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]

[project.optional-dependencies]
cuda12 = [
    "cupy-cuda12x",
    "nvmath-python[cu12]>=0.7.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipython>=9.7.0",
    "libigl>=2.6.1",
    "matplotlib>=3.10.7",
    "pytest>=8.4.2",
    "ruff>=0.14.3",
    "scikit-fem>=11.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
